name: CI Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Шаг для Checkout (извлечение кода)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установка Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint nose coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Шаг для Линтинга (после Checkout)
      - name: Lint with flake8
        run: |
          # Останавливает сборку при синтаксических ошибках
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Lint with pylint
        run: |
          pylint service

      # 5. Шаг для запуска Unit тестов (после Линтинга)
      - name: Run unit tests with nosetests
        run: |
          nosetests --with-spec --spec-color --with-coverage --cover-package=service
